package system

import (
	"database/sql"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-chi/chi/v5"

	"jotter/backend/internal/db"
	"jotter/backend/internal/features/common"
	"jotter/backend/internal/features/settings"
)

func RegisterRoutes(r chi.Router, tasksDir string) {
	r.Post("/system/sync", func(w http.ResponseWriter, r *http.Request) {
		// Load global settings
		globalSettings, err := settings.LoadSettings(tasksDir)
		if err != nil {
			common.SendError(w, http.StatusInternalServerError, fmt.Sprintf("Failed to load settings: %v", err))
			return
		}

		// 1. Fetch all projects from DB
		rows, err := db.DB.Query("SELECT id, git_remote FROM projects")
		if err != nil {
			common.SendError(w, http.StatusInternalServerError, err.Error())
			return
		}
		defer rows.Close()

		var projectsToSync []struct {
			id        string
			remoteURL string
		}
		var ignoredProjects []string

		for rows.Next() {
			var id string
			var remote sql.NullString
			if err := rows.Scan(&id, &remote); err != nil {
				continue
			}

			remoteURL := ""
			if remote.Valid {
				remoteURL = remote.String
			}

			// If project has an individual remote configured, it should be auto-ignored by the global sync,
			// and synced individually.
			if remoteURL != "" {
				ignoredProjects = append(ignoredProjects, id)
				projectsToSync = append(projectsToSync, struct {
					id        string
					remoteURL string
				}{id: id, remoteURL: remoteURL})
			} else if globalSettings.GitRemoteURL == "" {
				// If no global sync is configured, still allow individual sync if the project folder is a git repo
				projectsToSync = append(projectsToSync, struct {
					id        string
					remoteURL string
				}{id: id, remoteURL: ""})
			}
		}

		var gitErrors []string

		// 2. Perform Global Sync if configured
		if globalSettings.GitRemoteURL != "" {
			// Write .gitignore dynamically to ignore projects with individual remotes and temporary files
			var gitignoreContent strings.Builder
			gitignoreContent.WriteString("# Auto-generated by Jotter global git sync\n*.tmp\ntasks.db\ntasks.db-*\nsettings.json\n")
			for _, pID := range ignoredProjects {
				gitignoreContent.WriteString(pID + "/\n")
			}
			gitignorePath := filepath.Join(tasksDir, ".gitignore")
			_ = os.WriteFile(gitignorePath, []byte(gitignoreContent.String()), 0644)

			// Perform Git Sync for the entire workspace
			if errSync := common.GitSync(tasksDir, globalSettings.GitRemoteURL); errSync != nil {
				gitErrors = append(gitErrors, fmt.Sprintf("Workspace: %v", errSync))
			}
		}

		// 3. Perform Git Sync for each individual project
		for _, proj := range projectsToSync {
			projectPath := filepath.Join(tasksDir, proj.id)
			if errSync := common.GitSync(projectPath, proj.remoteURL); errSync != nil {
				gitErrors = append(gitErrors, fmt.Sprintf("Project '%s': %v", proj.id, errSync))
			}
		}

		if len(gitErrors) > 0 {
			common.SendError(w, http.StatusConflict, fmt.Sprintf("Git Synchronization issues:\n%s", strings.Join(gitErrors, "\n")))
			return
		}

		// 4. Database Index Sync
		count, err := SyncDBWithFiles(tasksDir)
		if err != nil {
			common.SendError(w, http.StatusInternalServerError, fmt.Sprintf("Database Synchronization failed: %v", err))
			return
		}

		common.SendJSON(w, http.StatusOK, map[string]interface{}{
			"status":             "success",
			"synchronized_tasks": count,
		})
	})
}
