package system

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"jotter/backend/internal/features/settings"
	"jotter/backend/internal/features/task"
)

// Service defines synchronization operations for the workspace
type Service interface {
	Sync(ctx context.Context, tasksDir string) (int, error)
	SyncDBOnly(ctx context.Context, tasksDir string) (int, error)
}

type systemService struct {
	dbRepo       DBRepository
	fileRepo     FileRepository
	settingsRepo settings.FileRepository
}

// NewService creates a new system service instance
func NewService(dbRepo DBRepository, fileRepo FileRepository, settingsRepo settings.FileRepository) Service {
	return &systemService{
		dbRepo:       dbRepo,
		fileRepo:     fileRepo,
		settingsRepo: settingsRepo,
	}
}

func (s *systemService) Sync(ctx context.Context, tasksDir string) (int, error) {
	// Load global settings
	globalSettings, err := s.settingsRepo.LoadSettings(tasksDir)
	if err != nil {
		return 0, fmt.Errorf("failed to load settings: %w", err)
	}

	// 1. Fetch all projects from DB
	dbProjects, err := s.dbRepo.GetProjects(ctx)
	if err != nil {
		return 0, err
	}

	var projectsToSync []ProjectSyncInfo
	var ignoredProjects []string

	for _, p := range dbProjects {
		if p.RemoteURL != "" {
			ignoredProjects = append(ignoredProjects, p.ID)
			projectsToSync = append(projectsToSync, p)
		} else if globalSettings.GitRemoteURL == "" {
			projectsToSync = append(projectsToSync, ProjectSyncInfo{ID: p.ID, RemoteURL: ""})
		}
	}

	var gitErrors []string

	// 2. Perform Global Sync if configured
	if globalSettings.GitRemoteURL != "" {
		// Write .gitignore dynamically
		var gitignoreContent strings.Builder
		gitignoreContent.WriteString("# Auto-generated by Jotter global git sync\n*.tmp\ntasks.db\ntasks.db-*\nsettings.json\n")
		for _, pID := range ignoredProjects {
			gitignoreContent.WriteString(pID + "/\n")
		}
		gitignorePath := filepath.Join(tasksDir, ".gitignore")
		_ = s.fileRepo.WriteFile(gitignorePath, []byte(gitignoreContent.String()))

		// Perform Git Sync for the entire workspace
		if errSync := s.fileRepo.GitSync(tasksDir, globalSettings.GitRemoteURL); errSync != nil {
			gitErrors = append(gitErrors, fmt.Sprintf("Workspace: %v", errSync))
		}
	}

	// 3. Perform Git Sync for each individual project
	for _, proj := range projectsToSync {
		projectPath := filepath.Join(tasksDir, proj.ID)
		if errSync := s.fileRepo.GitSync(projectPath, proj.RemoteURL); errSync != nil {
			gitErrors = append(gitErrors, fmt.Sprintf("Project '%s': %v", proj.ID, errSync))
		}
	}

	if len(gitErrors) > 0 {
		return 0, fmt.Errorf("Git Synchronization issues:\n%s", strings.Join(gitErrors, "\n"))
	}

	// 4. Database Index Sync
	return s.SyncDBOnly(ctx, tasksDir)
}

func (s *systemService) SyncDBOnly(ctx context.Context, tasksDir string) (int, error) {
	// 1. Load Projects registry
	projectsData, err := s.fileRepo.LoadProjectsFile(tasksDir)
	if err != nil {
		return 0, err
	}

	// 2. Scan Projects directories to sync Buckets and Tasks
	entries, err := s.fileRepo.ReadDir(tasksDir)
	if err != nil {
		return 0, err
	}

	var buckets []BucketSyncInfo
	var tasks []TaskSyncInfo

	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		pID := entry.Name()
		projectDir := filepath.Join(tasksDir, pID)

		// 1. Load Buckets
		bucketsFile := filepath.Join(projectDir, "buckets.json")
		if bData, err := s.fileRepo.ReadFile(bucketsFile); err == nil {
			var rawBuckets []map[string]interface{}
			if err := json.Unmarshal(bData, &rawBuckets); err == nil {
				for _, b := range rawBuckets {
					bName := b["name"].(string)
					bTitle := b["title"].(string)
					bSubtitle, _ := b["subtitle"].(string)
					bPos := b["position"].(float64)
					bLayout, _ := b["layout"].(string)
					if bLayout == "" {
						bLayout = "list"
					}
					bDefault, _ := b["is_default"].(bool)

					var bColor *string
					if c, ok := b["color"].(string); ok {
						bColor = &c
					}

					var bMaxTasks *int
					if m, ok := b["max_tasks"].(float64); ok {
						v := int(m)
						bMaxTasks = &v
					}

					buckets = append(buckets, BucketSyncInfo{
						ProjectID: pID,
						Name:      bName,
						Title:     bTitle,
						Subtitle:  bSubtitle,
						Position:  bPos,
						Layout:    bLayout,
						IsDefault: bDefault,
						Color:     bColor,
						MaxTasks:  bMaxTasks,
					})
				}
			}
		}

		// 2. Load Tasks
		files, err := s.fileRepo.ReadDir(projectDir)
		if err != nil {
			continue
		}

		// Look up project auto-pruning threshold from loaded registry
		var doneCleanPeriod int64
		for _, p := range projectsData {
			if p["id"] == pID {
				if p["done_clean_period"] != nil {
					switch v := p["done_clean_period"].(type) {
					case float64:
						doneCleanPeriod = int64(v)
					case int:
						doneCleanPeriod = int64(v)
					case int64:
						doneCleanPeriod = v
					}
				}
				break
			}
		}

		for _, f := range files {
			if f.IsDir() || !strings.HasSuffix(f.Name(), ".md") {
				continue
			}

			filePath := filepath.Join(projectDir, f.Name())
			fileContent, errRead := s.fileRepo.ReadFile(filePath)
			if errRead != nil {
				continue
			}

			fm, body, errParse := task.ParseFrontmatter(string(fileContent))
			if errParse == nil {
				taskID := strings.TrimSuffix(f.Name(), ".md")

				// --- Done Task Auto-Pruning ---
				if doneCleanPeriod > 0 && fm.Bucket == "done" {
					updatedAt, errTime := time.Parse(time.RFC3339Nano, fm.UpdatedAt)
					if errTime == nil {
						ageDays := int64(time.Since(updatedAt).Hours() / 24)
						if ageDays >= doneCleanPeriod {
							_ = s.fileRepo.RemoveFile(filePath)
							_ = s.fileRepo.RemoveDirAll(filepath.Join(projectDir, taskID+".attachments"))
							continue
						}
					}
				}

				idVal := fm.ID
				if idVal == "" {
					idVal = taskID
				}

				tasks = append(tasks, TaskSyncInfo{
					ID:          idVal,
					ProjectID:   pID,
					Title:       fm.Title,
					Bucket:      fm.Bucket,
					Position:    fm.Position,
					Tags:        fm.Tags,
					Attachments: fm.Attachments,
					Filename:    f.Name(),
					Body:        body,
					DueDate:     fm.DueDate,
					PlannedDate: fm.PlannedDate,
					Priority:    fm.Priority,
					Color:       fm.Color,
					CreatedAt:   fm.CreatedAt,
					UpdatedAt:   fm.UpdatedAt,
				})
			}
		}
	}

	// 3. Rebuild database tables transactionally
	return s.dbRepo.RebuildIndex(ctx, projectsData, buckets, tasks)
}
